export const khodams = [
  "Sapu Lidi",
  "Tengkulak Eskrim",
  "Gunung Kembar",
  "Sendal Jepit",
  "Bakso Mercon",
  "Kucing Garong",
  "Bantal Guling",
  "Tuyul Botak",
  "Pocong Internasional",
  "Kecoa Terbang",
  "Jamu Gendong",
  "Gethuk Lindri",
  "Buto Ijo",
  "Tikus Got",
  "Sandal Hilang",
  "Kue Putu",
  "Cicak Dinding",
  "Cilok Molor",
  "Ondel-ondel",
  "Keong Racun",
  "Bawang Bombay",
  "Cendol Dawet",
  "Sate Kelinci",
  "Kuda Lumping",
  "Setan Belang",
  "Semut Rangrang",
  "Pisang Goreng",
  "Jenglot Nyasar",
  "Genderuwo Gaul",
  "Pecel Lele",
  "Bebek Angsa",
  "Hantu Jeruk Purut",
  "Kuntilanak Centil",
  "Bakpao Setan",
  "Siomay Banjir",
  "Kecap Manis",
  "Wewe Gombel",
  "Babi Ngepet",
  "Mie Ayam",
  "Sundel Bolong",
  "Kunyit Asam",
  "Setan Koplo",
  "Gula Jawa",
  "Tahu Bulat",
  "Pocong Joget",
  "Bakwan Jagung",
  "Hantu Kerupuk",
  "Kuda Nil",
  "Sate Padang",
  "Roti Buaya",
  "Buto Cakil",
  "Bubur Ayam",
  "Hantu Gorengan",
  "Soto Betawi",
  "Poci Teh",
  "Barongsai Mabuk",
  "Gado-gado",
  "Kembang Tujuh Rupa",
  "Goyang Karawang",
  "Ikan Asin"
];