export const khodams = [
  "Sapu Lidi",
  "Tengkulak Eskrim",
  "Gunung Kembar",
  "Sendal Jepit",
  "Bakso Mercon",
  "Kucing Garong",
  "Bantal Guling",
  "Tuyul Botak",
  "Pocong Internasional",
  "Kecoa Terbang",
  "Jamu Gendong",
  "Gethuk Lindri",
  "Buto Ijo",
  "Tikus Got",
  "Sandal Hilang",
  "Kue Putu",
  "Cicak Dinding",
  "Cilok Molor",
  "Ondel-ondel",
  "Keong Racun",
  "Bawang Bombay",
  "Cendol Dawet",
  "Sate Kelinci",
  "Kuda Lumping",
  "Setan Belang",
  "Semut Rangrang",
  "Pisang Goreng",
  "Jenglot Nyasar",
  "Genderuwo Gaul",
  "Tengkulak Eskrim",
  "Bebek Angsa",
  "Hantu Jeruk Purut",
  "Kuntilanak Centil",
  "Bakpao Setan",
  "Siomay Banjir",
  "Kecap Manis",
  "Wewe Gombel",
  "Babi Ngepet",
  "Mie Ayam",
  "Sundel Bolong",
  "Kunyit Asam",
  "Setan Koplo",
  "Gula Jawa",
  "Tahu Bulat",
  "Pocong Joget",
  "Bakwan Jagung",
  "Hantu Kerupuk",
  "Kuda Nil",
  "Sate Padang",
  "Roti Buaya",
  "Buto Cakil",
  "Bubur Ayam",
  "Hantu Gorengan",
  "Soto Betawi",
  "Poci Teh",
  "Barongsai Mabuk",
  "Gado-gado",
  "Kembang Tujuh Rupa",
  "Goyang Karawang",
  "Ikan Asin",
  "Naga Bonar",
  "Setan Kekenyangan",
  "Badak Bercula Satu",
  "Burung Hantu Betawi",
  "Kerak Telor",
  "Kepiting Rebus",
  "Siomay Bandung",
  "Bakwan Malang",
  "Warteg Berjalan",
  "Sambal Matah",
  "Kopi Tubruk",
  "Lele Terbang",
  "Cacing Gila",
  "Durian Montong",
  "Hantu Penghuni Kos",
  "Maling Piring",
  "Sate Kere",
  "Ikan Hiu",
  "Tahu Sumedang",
  "Ubi Cilembu",
  "Roti Bakar",
  "Es Cendol",
  "Nasi Goreng Mafia",
  "Dewa Pencak Silat",
  "Pempek Palembang",
  "Teh Poci",
  "Setan Merinding",
  "Kolor Ijo",
  "Jeruk Bali",
  "Sambal Terasi",
  "Martabak Manis",
  "Keripik Singkong",
  "Burung Camar",
  "Jembatan Ancol",
  "Pisang Sale",
  "Setan Kelaparan",
  "Kopi Luwak",
  "Monyet Sirkus",
  "Bubur Kacang Hijau",
  "Nasi Kucing",
  "Setan Botak",
  "Klepon Kenyal",
  "Kerupuk Mlarat",
  "Rendang Sapi",
  "Kolak Pisang",
  "Es Doger",
  "Ondel-ondel Gendut",
  "Bajigur",
  "Tengkulak Nasi",
  "Kue Cubit",
  "Kue Pancong",
  "Ceker Setan",
  "Bebek Madura",
  "Hantu Sate",
  "Kue Apem",
  "Walang Sangit",
  "Bajing Loncat",
  "Nasi Uduk",
  "Ayam Geprek",
  "Setan Pelupa",
  "Lemper Ayam",
  "Serabi Solo",
  "Kue Lapis",
  "Tengkleng",
  "Pisang Molen",
  "Bubur Manado",
  "Pecel Lele",
  "Ikan Bakar",
  "Kue Lapis Legit",
  "Lontong Sayur",
  "Tahu Campur",
  "Kue Talam",
  "Keripik Tempe",
  "Bubur Candil",
  "Setan Penasaran",
  "Kacang Hijau",
  "Ayam Penyet",
  "Tahu Tek",
  "Kue Mangkok",
  "Kerupuk Kulit",
  "Nasi Timbel",
  "Setan Latah",
  "Bakso Beranak",
  "Ayam Betutu",
  "Kue Putu Mayang",
  "Gurame Bakar",
  "Sop Buntut",
  "Setan Gendut",
  "Tahu Petis",
  "Lumpia Semarang",
  "Ketoprak Jakarta",
  "Sate Madura",
  "Nasi Krawu",
  "Setan Gabut",
  "Gado-Gado Betawi",
  "Es Campur",
  "Klepon",
  "Soto Ayam",
  "Setan Galau",
  "Serabi Notosuman",
  "Pisang Coklat",
  "Bakmi Jawa",
  "Setan Sombong",
  "Es Teler",
  "Es Pisang Ijo",
  "Soto Lamongan",
  "Setan Baper",
  "Setan Kepo",
  "Singa Terbang",
  "Gajah Berdasi",
  "Nenek Lampir",
  "Kucing Rasta",
  "Kupu-Kupu Malam",
  "Buaya Darat",
  "Cacing Kepanasan",
  "Ikan Cupang",
  "Naga Api",
  "Kera Sakti",
  "Tikus Ninja",
  "Rusa Belang",
  "Babi Hutan",
  "Ular Piton",
  "Kuda Zebra",
  "Elang Perkasa",
  "Harimau Sumatra",
  "Laba-Laba Sakti",
  "Bunglon Gaib",
  "Gorila Raksasa",
  "Kadal Gila",
  "Hiu Putih",
  "Unta Berpunuk",
  "Kancil Licik",
  "Badak Beruntung",
  "Beruang Madu",
  "Serigala Bulu Emas",
  "Burung Phoenix",
  "Kelelawar Malam",
  "Hantu Air",
  "Raja Hutan",
  "Putri Duyung",
  "Naga Biru",
  "Paus Pembunuh",
  "Lebah Madu",
  "Kuda Pegasus",
  "Burung Garuda",
  "Macan Tutul",
  "Elang Hitam",
  "Srigala Pemburu",
  "Kucing Anggora",
  "Hantu Laut",
  "Putri Salju",
  "Duyung Hijau",
  "Hantu Gentayangan",
  "Manusia Serigala",
  "Jin Lampu",
  "Hantu Bayangan",
  "Raksasa Hijau",
  "Setan Ganas",
  "Hantu Padang Pasir",
  "Tengkorak Berjalan",
  "Zombie Pemakan Otak",
  "Mumi Mesir",
  "Drakula",
  "Vampir Malam",
  "Hantu Pohon",
  "Malaikat Kegelapan",
  "Iblis Jahat",
  "Demon Merah",
  "Roh Jahat",
  "Penjaga Neraka",
  "Hantu Kabut",
  "Hantu Tanah",
  "Jin Batu",
  "Jin Air",
  "Jin Angin",
  "Jin Api",
  "Naga Hitam",
  "Hantu Merah",
  "Hantu Hijau",
  "Hantu Kuning",
  "Hantu Putih",
  "Hantu Biru",
  "Setan Hitam",
  "Setan Putih",
  "Setan Merah",
  "Setan Hijau",
  "Setan Kuning",
  "Setan Biru",
  "Pocong Terbang",
  "Pocong Merah",
  "Pocong Hijau",
  "Pocong Biru",
  "Pocong Kuning",
  "Pocong Putih",
  "Kuntilanak Merah",
  "Kuntilanak Hijau",
  "Kuntilanak Biru",
  "Kuntilanak Kuning",
  "Kuntilanak Putih",
  "Kuntilanak Hitam",
  "Tuyul Kecil",
  "Tuyul Besar",
  "Tuyul Merah",
  "Tuyul Hijau",
  "Tuyul Kuning",
  "Tuyul Biru",
  "Tuyul Putih",
  "Genderuwo Besar",
  "Genderuwo Kecil",
  "Genderuwo Merah",
  "Genderuwo Hijau",
  "Genderuwo Biru",
  "Genderuwo Kuning",
  "Genderuwo Putih",
  "Wewe Gombel Merah",
  "Wewe Gombel Hijau",
  "Wewe Gombel Biru",
  "Wewe Gombel Kuning",
  "Wewe Gombel Putih",
  "Wewe Gombel Hitam",
];
